# -*- coding: utf-8 -*-
"""1.10zeros_10ones_10fives.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMy3MJgJBpKtDde0ZgRNUTvNnJUR9XOI
"""

'''1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 five'''

#importing numpy lib
import numpy as np

# Creating arrays of 10 zeros, 10 ones, and 10 fives
zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = np.full(10, 5)

zeros_array, ones_array, fives_array