# -*- coding: utf-8 -*-
"""3x3_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMy3MJgJBpKtDde0ZgRNUTvNnJUR9XOI
"""

'''2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.'''

#importing numpy lib
import numpy as np

# Creating a 3x3 matrix with values ranging from 2 to 10
matrix_3x3 = np.arange(2, 11).reshape(3, 3)

matrix_3x3
