# -*- coding: utf-8 -*-
"""12_to_38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMy3MJgJBpKtDde0ZgRNUTvNnJUR9XOI
"""

'''3. Write a NumPy program to create an array with values ranging from 12 to 38.'''

#importing numpy lib
import numpy as np

# Creating an array with values ranging from 12 to 38
array_12_to_38 = np.arange(12, 39)

array_12_to_38

