# -*- coding: utf-8 -*-
"""list_and_tuple_to_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMy3MJgJBpKtDde0ZgRNUTvNnJUR9XOI
"""

'''4. Write a NumPy program to convert a list and tuple into arrays.
Input: my_list = [1, 2, 3, 4, 5, 6, 7, 8]
Input: my_tuple = ([8, 4, 6], [1, 2, 3])'''

#importing numpy lib
import numpy as np

# Input data
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_tuple = ([8, 4, 6], [1, 2, 3])

# Converting list and tuple to numpy arrays
array_from_list = np.array(my_list)
array_from_tuple = np.array(my_tuple)

# Output the arrays
print("Array from list:", array_from_list)
print("Array from tuple:", array_from_tuple)


