# -*- coding: utf-8 -*-
"""1.list_into_numpy_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMy3MJgJBpKtDde0ZgRNUTvNnJUR9XOI
"""

'''1. Convert the below list into numpy array then display the array
 Input: my_list = [1, 2, 3, 4, 5] '''

#importing numpy lib
import numpy as np

#definig list
my_list = [1, 2, 3, 4, 5]

#converting list to numpy array
np_array = np.array(my_list)

#printing the array
np_array
