# -*- coding: utf-8 -*-
"""2.first&last_index_of_numpy_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMy3MJgJBpKtDde0ZgRNUTvNnJUR9XOI
"""

'''2. Convert the below list into a numpy array then display the array
then display the first and last index and then multiply each element by 2 and display the result.
 Input: my_list = [1, 2, 3, 4, 5] '''

#importing numpy lib
import numpy as np

my_list = [1, 2, 3, 4, 5]
np_array = np.array(my_list)

# Displaying the first and last index
first_index_value = np_array[0]
last_index_value = np_array[-1]

# Multiplying each element by 2
multiplied_array = np_array * 2


np_array, first_index_value, last_index_value, multiplied_array